// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvEYxjHTZRSln9jBAeISSskYVEctjFll0',
    appId: '1:620361053552:web:d4537d729b766d504dcbb5',
    messagingSenderId: '620361053552',
    projectId: 'rentals-auth-e518d',
    authDomain: 'rentals-auth-e518d.firebaseapp.com',
    storageBucket: 'rentals-auth-e518d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0srMvl4Dlxy7IIrpVIgSD7A10p0xD-0',
    appId: '1:620361053552:android:aca368fe7c86e5294dcbb5',
    messagingSenderId: '620361053552',
    projectId: 'rentals-auth-e518d',
    storageBucket: 'rentals-auth-e518d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvpgWSerO92uqHwygSfzQTqEXKDomK7M',
    appId: '1:620361053552:ios:a4ea7a2b5758488d4dcbb5',
    messagingSenderId: '620361053552',
    projectId: 'rentals-auth-e518d',
    storageBucket: 'rentals-auth-e518d.appspot.com',
    iosClientId: '620361053552-6ulj50l271n52nchnhulhug6n2fk7lhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvpgWSerO92uqHwygSfzQTqEXKDomK7M',
    appId: '1:620361053552:ios:a4ea7a2b5758488d4dcbb5',
    messagingSenderId: '620361053552',
    projectId: 'rentals-auth-e518d',
    storageBucket: 'rentals-auth-e518d.appspot.com',
    iosClientId: '620361053552-6ulj50l271n52nchnhulhug6n2fk7lhg.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalsApp',
  );
}
